/**
 * Validator Node Address Registry
 *
 * Static mapping of Certen validator node addresses across all non-EVM chains.
 * These are the addresses that validators use to submit anchors and proofs.
 *
 * EVM chains share a single ETH address per validator (from ETH_PRIVATE_KEY).
 * Non-EVM chains each have unique addresses per validator.
 *
 * Generated by: independant_validator/scripts/non-evm-keygen/generate.mjs
 */

export interface ValidatorAddresses {
  solana: string;
  aptos: string;
  sui: string;
  near: string;
  ton: string;
  evm: string;
}

export const VALIDATOR_ADDRESSES: Record<string, ValidatorAddresses> = {
  'validator-1': {
    solana: 'HcLBCDeRPbtiox9bpNfWiAf1BD5nDnXpzLzxYBxmapej',
    aptos: '0xed29b2866f24e04c6217276961ab8ec6e07102dabea999a6edb07bd35a4ab408',
    sui: '0x16e4cfaa4df41a7a00862a077de11d444e65431ea60cf75ba5e6019617f482b2',
    near: 'certen-v1.testnet',
    ton: 'kQCwjPq0JEr23SxQ50xW4Tp3-oIFnzX4rCd2pSxo1M7QrLVU',
    evm: '0x2b7d6d99aB37a7c03cE732E6274Db3Fb69BcffE8',
  },
  'validator-2': {
    solana: 'CJGLotVqEVZcwnAH7w1UbKh4UyvLXhDKgUmwbNMJz4ij',
    aptos: '0xc14ec969096d4e5b7196ded43feb0cc7a9ab7db02698a91d85da2d9088dc5896',
    sui: '0x620c985b5e0e6756190b259ff43ac3767794215b7ce04ced9232d6e8394b2578',
    near: 'certen-v2.testnet',
    ton: 'kQCbzQQisLezzDnymQ5jD2P-wuStq8mtzulsSh4Vxo7-iotw',
    evm: '0x518273099F5c4b87eEA65141931B78012dfE5c7d',
  },
  'validator-3': {
    solana: '9qqTiFryMda1hx84jvKCTeDEasesWrqvG1wvJ95yrup8',
    aptos: '0x82285b1ea3b39c1cd8b09df2bf446042f6f427eb43e819fe65daabb1541d0a10',
    sui: '0xe5d65f185aa137c4f5067633f1a069cccd96adf1aecfc8fe96e4d1f542621b38',
    near: 'certen-v3.testnet',
    ton: 'kQCZK4L8bDafUWGrUqo749EPDsEl9uKUhN1CMHjTbVvvdzn0',
    evm: '0xa4fA4209FDE5340B0D5b36522a34641a2d50C7c6',
  },
  'validator-4': {
    solana: 'BSdaGufj1qyj5KV3nqC44gi4KEBw5uwS24PpYcsk4zbi',
    aptos: '0xec2609d532747fb58967e5b381698ffcf73387950254905906778be94768842d',
    sui: '0xcd3b3071ae5c680d307e35ccc526b8909fdcf61f31394fcd6adfaeb00216cb1d',
    near: 'certen-v4.testnet',
    ton: 'kQDw08deQtbIw2jlaEv6_Pvdst1XbvNVvE-ZtjI9XTNsC_EG',
    evm: '0x6Ff54041Afef809e93ce6B570545069d2764783f',
  },
  'validator-5': {
    solana: '5PwGsUpEXQiYcrvNUntsAgMFshcVcQA4S37VUFq4wNhh',
    aptos: '0x3fb4ba981adaa8c68e800443419c64dcfbe0f89fdc5f4f66c2428e05ad054646',
    sui: '0x1775d0d224dcdbc4ea49760f40c5d113e70cb4a46ca0b9295fd4ad7a9f0f463a',
    near: 'certen-v5.testnet',
    ton: 'kQBsYAjy3HcYSnwtXB3wo3hy5N5971r7tBD9QiKbGmJV3owP',
    evm: '0xA9E0d9103D39B3e3c83C9c576dE8BBB00C15d5f4',
  },
  'validator-6': {
    solana: 'HHMTH3tETHARh8SLQAEdhKbTMr6G1TeYPTdhVs8J8J6H',
    aptos: '0x035038447a9ca71a406038f326eebd1df62dc37e9e15e6ab5fe885cb1bdc3237',
    sui: '0x4920bdfbbe18417ffd83934368424417d417dff3f9bf32bb8b6a7ed7f5759fef',
    near: 'certen-v6.testnet',
    ton: 'kQDMVPBKo8oL-FnaoY2S_Wj-yAJztc56dQ0i74K9kTupsCHc',
    evm: '0xd1AE92EB6A76d1B9e63fd0a63C14E5B55e36D5a5',
  },
  'validator-7': {
    solana: '2idWPeQ8jca99bRsjrFEbt1PrVkrEpbTZvpTLSFwhHi6',
    aptos: '0x429dd6e7327eb41f66b9be65b034bccbf8f85f2b92d54e606507bb5b97ca8db7',
    sui: '0x376c866f139108ef474f2052f508b314b9c8dd9a5f892e16c527969dc8e2ab21',
    near: 'certen-v7.testnet',
    ton: 'kQDhyjy4SNjBOxVkCj6oUuvLVAMVo0ftSgK0QoAspGsl2Xwk',
    evm: '0xF1F74f56950A14A66C9aFA364FDe55e88B3E1c14',
  },
};

/** Chains that have validator-specific addresses */
export const NON_EVM_CHAINS = ['solana', 'aptos', 'sui', 'near', 'ton'] as const;

/** Chain ID mapping for handler lookup */
export const CHAIN_HANDLER_IDS: Record<string, string> = {
  solana: 'solana-devnet',
  aptos: 'aptos-testnet',
  sui: 'sui-testnet',
  near: 'near-testnet',
  ton: 'ton-testnet',
  evm: 'sepolia',
};
