// DO NOT EDIT. Generated by gitlab.com/accumulatenetwork/accumulate/tools/cmd/gen-types.
/* eslint-disable @typescript-eslint/no-namespace */
export var ChainType;
(function (ChainType) {
    /** Unknown is used when the chain type is not known. */
    ChainType[ChainType["Unknown"] = 0] = "Unknown";
    /** Transaction holds transaction hashes. */
    ChainType[ChainType["Transaction"] = 1] = "Transaction";
    /** Anchor holds chain anchors. */
    ChainType[ChainType["Anchor"] = 2] = "Anchor";
    /** Index indexes other chains. */
    ChainType[ChainType["Index"] = 4] = "Index";
})(ChainType || (ChainType = {}));
/** @ignore */
(function (ChainType) {
    function fromObject(obj) {
        if (typeof obj === "number")
            return obj;
        return byName(obj);
    }
    ChainType.fromObject = fromObject;
    function byName(name) {
        switch (name.toLowerCase()) {
            case "unknown":
                return ChainType.Unknown;
            case "transaction":
                return ChainType.Transaction;
            case "anchor":
                return ChainType.Anchor;
            case "index":
                return ChainType.Index;
            default:
                throw new Error(`Unknown ChainType '${name}'`);
        }
    }
    ChainType.byName = byName;
    function getName(v) {
        switch (v) {
            case ChainType.Unknown:
                return "unknown";
            case ChainType.Transaction:
                return "transaction";
            case ChainType.Anchor:
                return "anchor";
            case ChainType.Index:
                return "index";
            default:
                throw new Error(`Unknown ChainType ${v}`);
        }
    }
    ChainType.getName = getName;
})(ChainType || (ChainType = {}));
//# sourceMappingURL=enums_gen.js.map